### ISSUE TITLE
Game Pause & Play Feature

### ISSUE THREAD

**Issue by sayedrafeeq** [montao/gamex#5]
Need a Game **Pause & Play** UX Feature (with Icons) anywhere on the screen of the game.

**Comment by montao** [comment]
Yes, I can program this functionality if we decide how it should look like.

**Comment by sayedrafeeq** [comment]
I will provide the draft design mockup for it.

**Comment by montao** [comment]
It works now https://github.com/montao/gamex/commit/a8f148034bea1a2f3fe9a22b199c502ac0312cfc

**Comment by sayedrafeeq** [comment]
Thank for update. 😀
